### ISSUE TITLE
Thank you for your esp32-rmt-ir.

### ISSUE THREAD

**Issue by Zhentao-Lin** [junkfix/esp32-rmt-ir#1]
I based on your code, call the arduino - esp32 RMT API, to write a library, https://github.com/Freenove/Freenove_IR_Lib_for_ESP32.
I've only finished the receiving part, and I haven't had time to try to write the sending part. But it works with arduino-esp32 version 3.0.x.
Thank you again for your contributions.

**Comment by Jan21021** [comment]
Also a warm thank you from me!! Its hard to understand the library since there is no comment. but after i got the hang of your approach, i could do changes very easy. you made a good and clean lib!!
